version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    entrypoint: /entrypoint.sh
    command: python /django_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/django_app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
